CREATE TABLE "LIFE".t_store_0909 (
  "ID" NUMBER(8) NOT NULL,
  "NAME" VARCHAR2(50 BYTE),
  short_name VARCHAR2(20 BYTE),
  area_code VARCHAR2(10 BYTE),
  "SORT" NUMBER(1),
  shop_agent_flag NUMBER(1),
  goods_agent_flag NUMBER(1),
  base_shop_name VARCHAR2(50 BYTE),
  create_time VARCHAR2(14 BYTE),
  update_time VARCHAR2(14 BYTE),
  address VARCHAR2(100 BYTE),
  sys_user_id NUMBER(8),
  update_user_id NUMBER(9),
  is_bs_account NUMBER(1),
  bs_manager_name VARCHAR2(50 BYTE),
  bs_manager_phone VARCHAR2(50 BYTE),
  fc_manager_name VARCHAR2(50 BYTE),
  fc_manager_phone VARCHAR2(50 BYTE),
  link_name VARCHAR2(50 BYTE),
  link_phone VARCHAR2(50 BYTE),
  link_fax VARCHAR2(50 BYTE),
  shop_class NUMBER(1),
  status NUMBER(1),
  is_valid NUMBER(1),
  item_edit_audit_flag NUMBER(1),
  item_publish_audit_flag NUMBER(1),
  shop_edit_audit_flag NUMBER(1),
  sync_gy_flag NUMBER(1),
  bs_scope VARCHAR2(200 BYTE),
  service_phone VARCHAR2(50 BYTE),
  area_id VARCHAR2(20 BYTE),
  merchid VARCHAR2(20 BYTE),
  stop_time VARCHAR2(14 BYTE),
  start_time VARCHAR2(14 BYTE)
);
ALTER TABLE "LIFE".t_store_0909 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;