CREATE TABLE "LIFE".tmp_t_shop_20131203 (
  "ID" NUMBER(8) NOT NULL,
  ac_shop_id NUMBER(8),
  "NAME" VARCHAR2(200 BYTE),
  short_name VARCHAR2(200 BYTE),
  area_code VARCHAR2(10 BYTE),
  "SORT" NUMBER(1),
  discount_detail VARCHAR2(100 BYTE),
  is_chain NUMBER(1),
  is_base_shop NUMBER(1),
  base_shop_name VARCHAR2(50 BYTE),
  create_time VARCHAR2(14 BYTE),
  update_time VARCHAR2(14 BYTE),
  start_time VARCHAR2(14 BYTE),
  stop_time VARCHAR2(14 BYTE),
  address VARCHAR2(500 BYTE),
  phone VARCHAR2(100 BYTE),
  open_time VARCHAR2(100 BYTE),
  bus_line VARCHAR2(400 BYTE),
  area VARCHAR2(20 BYTE),
  park_place VARCHAR2(20 BYTE),
  avg_spend NUMBER(8),
  room_num VARCHAR2(50 BYTE),
  map_long VARCHAR2(20 BYTE),
  map_dim VARCHAR2(20 BYTE),
  shop_user_id NUMBER(9),
  status NUMBER(9),
  is_valid NUMBER(1),
  shop_class NUMBER(1),
  logo VARCHAR2(100 BYTE),
  remark CLOB,
  map_type VARCHAR2(3 BYTE)
);