CREATE FORCE VIEW "LIFE".v_goods_info (g_id,g_payment_cash,g_payment_coin,g_payment_score,g_is_valid,g_iseckill,g_iseckill_price,g_cash_idgoods,g_coin_idgoods,g_score_idgoods,g_org_id,g_name,g_short_name,g_type_id,g_brand,g_create_time,g_update_time,g_market_content,g_web_path,g_source,g_market_price,g_shop_price,g_remark,g_post_flag,g_item_mode,g_start_time,g_stop_time,g_is_view,g_warm_prompt,g_group_flag,g_store_id,g_logistics_fee,g_logistics_fee_type,g_stock_num,g_region_code,g_region_codes,g_user_levels,g_property,g_tags) AS
select tis.id g_id,
       tis.cash_idgoods g_payment_cash,
       tis.coin_idgoods g_payment_coin,
       tis.score_idgoods g_payment_score,
       tis.is_valid g_is_valid,
       tis.iseckill g_iseckill,
       tis.iseckill_price g_iseckill_price,
       tis.cash_idgoods g_cash_idgoods,
       tis.coin_idgoods g_coin_idgoods,
       tis.score_idgoods g_score_idgoods,
       tis.org_id g_org_id,
       tis.name g_name,
       tis.short_name g_short_name,
       tis.type_id g_type_id,
       tis.brand g_brand,
       tis.create_time g_create_time,
       tis.update_time g_update_time,
       tis.market_content g_market_content,
       tis.img_path g_web_path,
       tis.source g_source,
       to_char(nvl(tis.market_price, 0), 'fm999999990.00') g_market_price,
       to_char(nvl(tis.shop_price, 0), 'fm999999990.00') g_shop_price,
       tis.remark g_remark,
       tis.post_flag g_post_flag,
       tis.item_mode g_item_mode,
       tis.sale_start_time g_start_time,
       tis.sale_stop_time g_stop_time,
       tis.is_view g_is_view,
       tis.warm_prompt g_warm_prompt,
       tis.group_flag g_group_flag,
       tis.store_id g_store_id,
       to_char(nvl(tis.logistics_fee, 0), 'fm999999990.00') g_logistics_fee,
       nvl(tis.logistics_fee_type, 0) g_logistics_fee_type,
       nvl(tis.stock_num, 0) g_stock_num,
       (select to_char(wm_concat(region_code)) region_code from t_item_sale_area_link area_link where tis.id = area_link.sale_id) g_region_code,
       (select to_char(wm_concat(region_code)) region_codes from t_item_sale_user_area_link user_area_link where tis.id = user_area_link.sale_id) g_region_codes,
       (select to_char(wm_concat(user_level)) user_levels from t_item_sale_user_level_link sale_user_level where tis.id = sale_user_level.sale_id) g_user_levels,
       (select to_char(wm_concat(param_value)) property from t_item_param item_param where tis.id = item_param.item_id) g_property,
       (select to_char(wm_concat(tag)) tags from t_item_tag item_tag where tis.id = item_tag.item_id) g_tags
  from t_item_sale tis
 where tis.status = 3
   and tis.is_valid = 1
;