var ajaxRequestUrl="";var returnMethodName="";var islogin;var product_request=false;var isshow=false;var islogin=false;var isshowback=true;var dialogWidth=500;var dialogHeight=300;var isopen=false;function isLogin(){var showAjax=new ajax();showAjax.url=CONT+"/fg/user/user.do?actionType=islogin";showAjax.callback=showResult;showAjax.cache=true;showAjax.send();function showResult(){if(showAjax.req.readyState==4){if(showAjax.req.status==200){var returnText=showAjax.req.responseText;islogin=returnText;if(islogin!='true'){show(CONT+'/fg/user/poplogin.do?actionType=gologin','ajaxdialog',false);showDiaLog();}else{invokeReturnMethod();showDiaLog();}
return;}else{}}}}
function ajaxOpenDialog(turl,methodName,thisshow,needLogin,tshowBack,pisopen,dwidth,dheight){ajaxRequestUrl=turl;dialogWidth=dwidth;dialogHeight=dheight;isopen=pisopen;clearDiaLog();returnMethodName=methodName;isshow=thisshow;if(tshowBack==false){isshowback=tshowBack;}else{isshowback=true;}
if(needLogin){isLogin();}else{invokeReturnMethod();showDiaLog();}}
function getLoginFormData(){var noValidateCode=document.getElementsByName('noValidateCode')[0].value;var userId=document.getElementsByName('userId')[0].value;var userPassword=document.getElementsByName('userPassword')[0].value;var retrunXml="<save>";retrunXml=retrunXml+"<type>userlogin</type>";retrunXml=retrunXml+"<userlogin>";retrunXml=retrunXml+"<noValidateCode>";retrunXml=retrunXml+escape(noValidateCode);retrunXml=retrunXml+"</noValidateCode>";retrunXml=retrunXml+"<userId>";retrunXml=retrunXml+escape(userId);retrunXml=retrunXml+"</userId>";retrunXml=retrunXml+"<userPassword>";retrunXml=retrunXml+escape(userPassword);retrunXml=retrunXml+"</userPassword>";retrunXml=retrunXml+"</userlogin>";retrunXml=retrunXml+"</save>";return retrunXml;}
function userAjaxLogin(){var thisUrl=CONT+"/fg/user/user.do?actionType=ajaxlogin";var appXml=getLoginFormData();var httpMethod="POST";var isXML=true;if(window.XMLHttpRequest){product_form_request=new XMLHttpRequest();if(product_form_request.overrideMimeType){product_form_request.overrideMimeType('text/xml');}}else if(window.ActiveXObject){try{product_form_request=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{product_form_request=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){}}}
if(!product_form_request){window.alert("不能创建XMLHttpRequest对象实例.");return false;}
product_form_request.onreadystatechange=function(){showloginInfo();}
product_form_request.open("POST",thisUrl,true);if(httpMethod=="POST"&&isXML){product_form_request.setRequestHeader("Content-Type","text/xml");product_form_request.setRequestHeader("charset","GBK");}else if(httpMethod=="POST"&&!isXML){product_form_request.setRequestHeader("Content-Type","application/x-www-form-urlencoded");}
if(window.ActiveXObject){product_form_request.setRequestHeader("If-Modified-Since","0");}
product_form_request.send(appXml);}
function showloginInfo(){if(product_form_request.readyState==4){if(product_form_request.status==200){var returnText=product_form_request.responseText;if(returnText=="login_error"){alert("用户名或者密码错误请检查后输入！");return;}
if(returnText=="login_success"){invokeReturnMethod();}}else{alert("服务暂停,请稍后访问!");}}}
function invokeReturnMethod(){if(isshow){if(isopen){show(ajaxRequestUrl,'ajaxdialog',false);return;}else{if(ajaxRequestUrl==window.location){location.reload(true);}else{window.location=ajaxRequestUrl;}
return;}}
if(window.XMLHttpRequest){product_request=new XMLHttpRequest();if(product_request.overrideMimeType){product_request.overrideMimeType('text/xml');}}else if(window.ActiveXObject){try{product_request=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{product_request=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){}}}
if(!product_request){window.alert("不能创建XMLHttpRequest对象实例.");return false;}
product_request.onreadystatechange=returnMethodName;product_request.open("GET",ajaxRequestUrl,true);product_request.send("");}
var leftn=screen.width/2-390;var topn=0;var myfullHeight=4000;var myfullWidth=screen.width;var gPopupMask;var gi=0;function showBackground(){gPopupMask=document.getElementById("popupMask")
var fullHeight=myfullHeight;var fullWidth=myfullWidth;var theBody=document.documentElement;var scTop=0;var scLeft=0;gPopupMask.style.display="block";gPopupMask.style.height=fullHeight+"px";gPopupMask.style.width=fullWidth+"px";gPopupMask.style.top=scTop+"px";gPopupMask.style.left=scLeft+"px";var ahrefs=document.getElementsByTagName('select');if(ahrefs.length>0){for(var i=0;i<ahrefs.length;i++){ahrefs[i].style.display='none';}}}
function hiddenBackground(){if(gPopupMask==null){return;}
gPopupMask.style.display="none";var ahrefs=document.getElementsByTagName('select');if(ahrefs.length>0){for(var i=0;i<ahrefs.length;i++){ahrefs[i].style.display='block';}}}
function clearDiaLog(){$("#ajaxdialog").innerHTML='';}
function showDiaLog(){if(isshowback){showBackground();}
$("#ajaxdialog").show();var oDialog=document.getElementById("ajaxdialog");var theBody=document.documentElement;var scTop=parseInt(theBody.scrollTop,10);var scLeft=parseInt(theBody.scrollLeft,10);var twidth=418;var theight=243;var scrollWidth=screen.width-40;var scrollHeight=screen.height-180;var top=0;top=document.documentElement.scrollTop;scLeft=(scrollWidth-dialogWidth)/2;scTop=top+(scrollHeight-dialogHeight)/2;oDialog.style.top=scTop+"px";oDialog.style.left=scLeft+"px";}
function hideDiaLog(){hiddenBackground();document.getElementById("ajaxdialog").innerHTML='&nbsp;';$("#ajaxdialog").hide();}