function load(divid,CON){var loadstr="<div  style='width:100px;height:21px;background-color:#f2f2f2;border:1px solid #dedede;padding-top:4px;padding-right:15px'>";loadstr=loadstr+"<img src='"+CON+"/images/load.gif' align='absmiddle'/>正在处理中...";loadstr=loadstr+"</div>";$('#'+divid).html(loadstr);}
function TrBgOn(TrBgid){TrBgid.style.backgroundColor="#fafafa";}
function TrBgOff(TrBgid){TrBgid.style.backgroundColor="#ffffff";}
function logout1(){document.userloginForm.requestPageUrl.value=window.top.location;document.userloginForm.actionType.value="logout";document.userloginForm.submit();}
function userLoginSubmitForm(){if(trim(document.getElementById('loginuserid').value)==""){alert("请输入登录帐号");document.getElementById('loginuserid').focus();return;}
if(!isMobile(trim(document.getElementById("loginuserid").value),true)){alert("请输入有效的手机号/乐e卡号。");document.getElementById("loginuserid").focus();return;}
if(trim(document.getElementById('loginuserpwd').value)==""){alert("请输入密码");document.getElementById('loginuserpwd').focus();return;}
if(document.getElementById('loginuserpwd').value.length!=6){alert('密码长度为6位。');}
if(document.getElementsByName('validateCode')[0].value==""){alert("验证码必须填写。");document.getElementsByName('validateCode')[0].focus();return;}
document.fguserForm.submit();}
function clearForm(){document.getElementsByName('bean.id')[0].value="";document.getElementsByName('bean.password')[0].value="";}
function gologin(){document.userloginForm.target="_blank";document.userloginForm.actionType.value="gologin";document.userloginForm.submit();}
function login(){document.userloginForm.requestPageUrl.value=encodeURIComponent(window.top.location);document.userloginForm.actionType.value="login";document.userloginForm.submit();}
function logout(){document.userloginForm.requestPageUrl.value=encodeURIComponent(window.top.location);document.userloginForm.actionType.value="logout";document.userloginForm.submit();}
function logout2(){document.userloginForm.requestPageUrl.value=encodeURIComponent(window.top.location);document.userloginForm.actionType.value="outlogin";document.userloginForm.submit();}
function regedit(){document.userloginForm.requestPageUrl.value=encodeURIComponent(window.top.location);document.userloginForm.actionType.value="regedit";document.userloginForm.submit();}
function removeConfig(removeurl){if(confirm("您确定清空该配置吗？")){window.open(removeurl,"",'left=2000,top=0,scrollbars=no,width=1,height=1');}}
function openConfig(configUrl){var leftn=screen.width/2-390;var topn=50;window.open(configUrl,"",'left='+leftn+',top='+topn+',scrollbars=yes,width=780,height=590');}
function refresh()
{this.location=this.location;}
function unkey(){var ahrefs=document.getElementsByTagName('a');if(ahrefs.length>0){for(var i=0;i<ahrefs.length;i++){if(ahrefs[i].className!="putKey"){ahrefs[i].href="javascript:void(0)";ahrefs[i].target="_top";ahrefs[i].style.cursor="point";}}}}
function fHideFocus(tName){var aTag=document.getElementsByTagName(tName);if(aTag.length>0){for(var i=0;i<aTag.length;i++){aTag[i].hideFocus=true;}}}
function initCart(){var thisUrl=CONT+"/fg/order/cart.do?actionType=ajaxgetcart";send_request(cartInfo,"POST",thisUrl,false,null);}
function cartInfo(){if(http_request.readyState==4){if(http_request.status==200){var returnXML=http_request.responseXML;var count=0;var tototal=0;if(returnXML&&returnXML.getElementsByTagName("count")&&returnXML.getElementsByTagName("count").item(0)!=null){count=returnXML.getElementsByTagName("count").item(0).firstChild.nodeValue;}
if(returnXML&&returnXML.getElementsByTagName("tototal")&&returnXML.getElementsByTagName("tototal").item(0)!=null){tototal=returnXML.getElementsByTagName("tototal").item(0).firstChild.nodeValue;}
document.getElementById("productCountsAndTotoalId").innerHTML=""+count;}else{}}}
function addCart(productId,numbers){document.cart.productId.value=productId;var num=numbers;if(numbers==null){num=1;}else{num=numbers;}
var cart=CART+"?actionType=addproduct&productId="+productId+"&number="+num;window.location.href=cart;document.cart.submit();}
function searchSubmitForm(){if(trim(document.psForm.key.value)==""||document.psForm.key.value=="请输入多个关键字"){alert("请输入商品关键字");document.psForm.key.value="";document.psForm.key.focus();return;}
document.psForm.submit();}
function search(_s){document.psForm.key.value=_s;searchSubmitForm();}
var coupon;function openCoupon(turl){var leftn=screen.width/2-411;var topn=50;if(coupon)coupon.close();coupon=window.open(turl,'','left='+leftn+',top='+topn+',scrollbars=yes,width=431,height=500');}
function flushValidateCode(){var validateImgObject=document.getElementById("validateImg");validateImgObject.src=CONT+"/ImageCaptchaServlet?time="+new Date();}
function jsuserAjaxLoginPop(){var thisUrl=CONT+"/fg/user/user.do?actionType=login";if(trim(document.getElementById('loginuserid').value)==""){alert("请输入登录手机号/乐e卡号");document.getElementById('loginuserid').focus();return;}
if(trim(document.getElementById('loginuserpwd').value)==""){alert("请输入密码");document.getElementById('loginuserpwd').focus();return;}
if(document.getElementById('loginuserpwd').value.length!=6){alert('密码长度为6位。');}
if(document.getElementById('validateCodeIdPop').value==""){alert("验证码必须填写。");document.getElementById('validateCodeIdPop').focus();return;}
var options={target:'#ajaxdialog'};$('#user_form').ajaxSubmit(options);}
function jsuserAjaxLogin(){var thisUrl=CONT+"/fg/user/user.do?actionType=login";if(trim(document.getElementById('loginuserid').value)==""){alert("请输入登录手机号/乐e卡号");document.getElementById('loginuserid').focus();return;}
if(!isMobile(trim(document.getElementById("loginuserid").value),true)){alert("请输入有效的手机号/乐e卡号。");document.getElementById("loginuserid").focus();return;}
if(trim(document.getElementById('loginuserpwd').value)==""){alert("请输入密码");document.getElementById('loginuserpwd').focus();return;}
if(document.getElementById('loginuserpwd').value.length!=6){alert('密码长度为6位。');}
if(document.getElementsByName('validateCode')[0].value==""){alert("验证码必须填写。");document.getElementsByName('validateCode')[0].focus();return;}
var options={target:'#ajaxdialog'};$('#user_form').ajaxSubmit(options);}
function jsuserAjaxLogin2(){if(trim(document.getElementsByName('loginCode')[0].value)==""){alert("请输入验证码");document.getElementsByName('loginCode')[0].focus();return;};var options={target:'#ajaxdialog'};$('#user_form').ajaxSubmit(options);}
function addFavoriteProduct(productId){var thisUrl=CONT+"/fg/product/productFav.do?actionType=addfavorite&productId="+productId;ajaxOpenDialog(CONT+"/fg/product/productFav.do?actionType=addfavorite&productId="+productId,false,true,true,true,true,418,248);}
function showTopUser(){var pageUrl=CONT+"/fg/user/user.do?actionType=showloginuser&time"+new Date();var showAjax=new ajax();showAjax.cache=false;showAjax.url=pageUrl;showAjax.callback=function(){showObjectResult();};showAjax.send();function showObjectResult(){if(showAjax.req.readyState==4){if(showAjax.req.status==200){var returnText=showAjax.req.responseText;var obj=returnText.parseJSON();if(obj.errormessage!=null){if(obj.errormessage=='no_user'){var s="[&nbsp;<a style='cursor:pointer' onclick='javascript:ajaxOpenDialog(top.location,false, true, true, true,false, 418,248);'><span>用户登录</span></a>&nbsp;]";$('#topuserinfo').innerHTML=s;document.getElementById('balancediv').innerHTML=obj.balance;return;}}else{if(obj.success=='true'){var s='您好';if(trim(obj.user.nickName)!=''){s=s+obj.user.nickName;}else{s=s+obj.user.mobile;}
if('VIP'==obj.user.card.cardClass){s=s+"，您是VIP会员";}else{s=s+"&nbsp;";}
s=s+"[<a href='"+CONT+"/fg/user/user.do?actionType=logout'>退出</a>]";document.getElementById('topuserinfo').innerHTML=s;document.getElementById('balancediv').innerHTML='<strong style="/padding-left:44px;"/>商城币'+obj.user.card.balance+'个</strong>';if(document.getElementById('virtualDeposit')!=null){document.getElementById('virtualDeposit').innerHTML=obj.user.card.balance;}
if($('#tabs-userlogin')!=null){var loginstr='';if(obj.user.nickname!=null&&obj.user.nickname!=''&&obj.user.nickname!='undefined'){loginstr=loginstr+'<ul><li style=\"padding-top:10px;\">昵&nbsp;&nbsp;称：'+obj.user.nickname+'</li>';}else{loginstr=loginstr+'<ul><li style=\"padding-top:10px;\">帐&nbsp;&nbsp;户：'+obj.user.mobile+'</li>';}
loginstr=loginstr+'<li style=\"padding-top:10px;\">卡&nbsp;&nbsp;号：'+obj.user.id+'</li>';loginstr=loginstr+"<li style=\"padding-top:10px;\" id=\"leftcode\">欢迎登录苏州移动商城！</li>";loginstr=loginstr+"<li style=\"padding-top:10px;\" id=\"leftuserbutton\"  style=\"float:left;width:180px;\">";loginstr=loginstr+"<div style=\"float:left;width:84px;text-align:left;display: block;background:url(images/xunika.gif) no-repeat 100% 0px;margin-left:0px;Cursor:pointer;height:24px;*height:19px;float:left;padding:5px 9px 0 12px!important;*padding:5px 9px 0 12px;color:#fff;\" ><a href=\"usercenter/usercenter.jsp\" ><span style=\"color:#fff;\">查看我的乐e卡</span></a></div>";loginstr=loginstr+"<div  style=\"float:left;text-align:left;display: block;background:url(images/tuichu_x.gif) no-repeat 100% 0px;margin-left:2px;Cursor:pointer;height:24px;*height:19px;float:left;padding:5px 15px 0 15px!important;*padding:5px 15px 0 15px;color:#fff;\"><a href=\"fg/user/user.do?actionType=logout\" ><span style=\"color:#fff;\">退出</span></a></div>";loginstr=loginstr+"</li></ul>";$('#tabs-userlogin').html(loginstr);}}}}}}}
function checkNumber(str){if(str==null||str==""){return false;}else if(str.length==0){return false;}else{for(i=0;i<str.length;i++){if(str.charAt(i)<'0'||str.charAt(i)>'9'){return false;break;}}}
return true;}
function leftUserLoginSubmitForm(divid){if(trim(document.getElementById('leftloginuserid').value)==""){alert("请输入手机号/乐e卡号");document.getElementById('leftloginuserid').focus();return;}
if(!checkNumber(document.getElementsByName('leftloginuserid')[0].value)){alert('手机号包含特殊字符不能提交。')
document.getElementById('leftloginuserid').focus();return;}
if(trim(document.getElementById('leftloginuserpwd').value)==""){alert("请输入密码");document.getElementById('leftloginuserpwd').focus();return;}
if(document.getElementById('leftloginuserpwd').value.length!=6){alert('密码长度为6位。');document.getElementById('leftloginuserpwd').focus();return;}
$('#leftloadding').show();$('#leftcode').hide();var pageUrl=CONT+"/fg/user/user.do?actionType=getcode&time"+new Date();pageUrl=pageUrl+"&bean.id="+document.getElementById('leftloginuserid').value;pageUrl=pageUrl+"&bean.password="+document.getElementById('leftloginuserpwd').value;var showAjax=new ajax();showAjax.cache=false;showAjax.url=pageUrl;showAjax.callback=function(){showObjectResult();};showAjax.send();function showObjectResult(){if(showAjax.req.readyState==4){if(showAjax.req.status==200){var returnText=showAjax.req.responseText;$('#leftloadding').hide();$('#leftcode').show();var obj=returnText.parseJSON();if(obj.errormessage!=null){if(obj.errormessage=='401'){alert('该用户非乐e卡用户，请先注册开通');return;}else if(obj.errormessage=='402'){alert('密码错误');return;}else if(obj.errormessage=='403'){alert('非苏州移动号码');return;}else if(obj.errormessage=='404'){alert('系统繁忙，稍后请重试');return;}else if(obj.errormessage=='405'){alert('用户密码为初密码123456');return;}else if(obj.errormessage=='406'){alert('IP地址鉴权失败');return;}else if(obj.errormessage=='407'){alert('查询错误');return;}else if(obj.errormessage=='408'){alert('账号被冻结');return;}else if(obj.errormessage=='409'){alert('账号被关闭');return;}else{alert('登录失败');}}else{if(obj.success=='true'){if(obj.msg=='getcode_suc'){$('#leftcode').html('验证码：<input  name="q" id="leftstorevcodex" type="text" class="text" style="width:40px;" value=""/>&nbsp;<a style="cursor:pointer"><img onclick="javascript:flushValidateCode()"  alt="点击重新获取验证码" id="validateImg" src="ImageCaptchaServlet" align="absmiddle"/></a>&nbsp;');var buttonHtml='&nbsp;<a style="cursor:pointer;" onclick="leftUserLoginSubmitForm2()"><img src="images/jsyd_sydl_an.gif"  align="absmiddle" border="0"/></a>&nbsp;';$('#leftuserbutton').html(buttonHtml);document.getElementById('leftloginuserid').disabled=true;document.getElementById('leftloginuserpwd').disabled=true;}else if(obj.msg=='login_suc'){showTopUser();}}}}}}
$('#leftloadding').show();$('#leftcode').hide();}
function leftUserLoginSubmitForm2(){if(trim(document.getElementById('leftstorevcodex').value)==""){alert("请输入验证码");document.getElementById('leftstorevcodex').focus();return;}
var pageUrl=CONT+"/fg/user/user.do?actionType=loginwithcode&time"+new Date();pageUrl=pageUrl+"&validatecode="+document.getElementById('leftstorevcodex').value;var showAjax=new ajax();showAjax.cache=false;showAjax.url=pageUrl;showAjax.callback=function(){showObjectResult();};$('#leftloadding').show();$('#leftcode').hide();$('#leftuserbutton').hide();showAjax.send();function showObjectResult(){if(showAjax.req.readyState==4){if(showAjax.req.status==200){var returnText=showAjax.req.responseText;if("validate_error"==trim(returnText)){$('#leftloadding').hide();alert("登录失败，验证码不正确。");$('#leftcode').show();$('#leftuserbutton').show();document.getElementsByName("leftstorevcodex")[0].value="";document.getElementById('leftstorevcodex').focus();flushValidateCode();return;}else{showTopUser();}}}}}
function leftStoreLoginSubmitForm(){if(trim(document.getElementById('storeid').value)==""){alert("请输入帐户");document.getElementById('storeid').focus();return;}
if(trim(document.getElementById('storepwd').value)==""){alert("请输入密码");document.getElementById('storepwd').focus();return;}
var pageUrl=CONT+"/store/login.do?actionType=jsonlogin";pageUrl=pageUrl+"&bean.email="+document.getElementById('storeid').value;pageUrl=pageUrl+"&bean.password="+document.getElementById('storepwd').value;pageUrl=pageUrl+"&validateCode="+document.getElementById('leftstorevcode').value;var showAjax=new ajax();showAjax.cache=false;showAjax.url=pageUrl;showAjax.callback=function(){showObjectResult();};showAjax.send();function showObjectResult(){if(showAjax.req.readyState==4){if(showAjax.req.status==200){var returnText=showAjax.req.responseText;var obj=returnText.parseJSON();if(obj.errormessage!=null){if(obj.errormessage=='validate_error'){alert('验证码不正确，请重新输入');}else if(obj.errormessage=='login_error'){alert('帐户密码不正确，请重新输入');}else if(obj.errormessage=='frozen'){alert('该商户或帐户被冻结，不能登录。');}else if(obj.errormessage=='black'){alert('该商户被加入黑名单，不能登录。');}
return;}else{if(obj.success=='true'){if(obj.msg=='login_suc'){window.location='store/manager/storeCenter.jsp?time='+new Date();}}}}}}}