for(var i = 0; i < 172; i++) { var scriptId = 'u' + i; window[scriptId] = document.getElementById(scriptId); }

$axure.eventManager.pageLoad(
function (e) {

});
gv_vAlignTable['u115'] = 'center';gv_vAlignTable['u21'] = 'top';gv_vAlignTable['u2'] = 'top';gv_vAlignTable['u79'] = 'center';gv_vAlignTable['u4'] = 'top';gv_vAlignTable['u153'] = 'top';gv_vAlignTable['u140'] = 'top';gv_vAlignTable['u17'] = 'top';gv_vAlignTable['u135'] = 'center';gv_vAlignTable['u151'] = 'top';gv_vAlignTable['u55'] = 'center';gv_vAlignTable['u101'] = 'center';gv_vAlignTable['u14'] = 'top';gv_vAlignTable['u105'] = 'center';gv_vAlignTable['u20'] = 'top';gv_vAlignTable['u67'] = 'center';gv_vAlignTable['u11'] = 'top';gv_vAlignTable['u6'] = 'top';gv_vAlignTable['u37'] = 'center';gv_vAlignTable['u75'] = 'center';gv_vAlignTable['u133'] = 'center';gv_vAlignTable['u89'] = 'center';gv_vAlignTable['u47'] = 'center';gv_vAlignTable['u103'] = 'center';gv_vAlignTable['u164'] = 'top';gv_vAlignTable['u99'] = 'center';gv_vAlignTable['u57'] = 'center';gv_vAlignTable['u16'] = 'top';gv_vAlignTable['u125'] = 'center';gv_vAlignTable['u41'] = 'center';gv_vAlignTable['u25'] = 'top';gv_vAlignTable['u149'] = 'top';gv_vAlignTable['u26'] = 'top';gv_vAlignTable['u119'] = 'center';gv_vAlignTable['u85'] = 'center';gv_vAlignTable['u51'] = 'center';gv_vAlignTable['u77'] = 'center';gv_vAlignTable['u166'] = 'top';gv_vAlignTable['u95'] = 'center';gv_vAlignTable['u61'] = 'center';gv_vAlignTable['u158'] = 'center';gv_vAlignTable['u33'] = 'center';gv_vAlignTable['u160'] = 'center';gv_vAlignTable['u71'] = 'center';gv_vAlignTable['u127'] = 'center';gv_vAlignTable['u43'] = 'center';gv_vAlignTable['u169'] = 'top';gv_vAlignTable['u168'] = 'top';gv_vAlignTable['u139'] = 'center';gv_vAlignTable['u87'] = 'center';gv_vAlignTable['u53'] = 'center';gv_vAlignTable['u121'] = 'center';gv_vAlignTable['u65'] = 'center';gv_vAlignTable['u109'] = 'center';gv_vAlignTable['u97'] = 'center';gv_vAlignTable['u123'] = 'center';gv_vAlignTable['u170'] = 'top';gv_vAlignTable['u81'] = 'center';gv_vAlignTable['u9'] = 'top';gv_vAlignTable['u73'] = 'center';gv_vAlignTable['u69'] = 'center';gv_vAlignTable['u163'] = 'center';gv_vAlignTable['u91'] = 'center';gv_vAlignTable['u131'] = 'center';gv_vAlignTable['u24'] = 'top';gv_vAlignTable['u13'] = 'top';gv_vAlignTable['u113'] = 'center';gv_vAlignTable['u29'] = 'top';gv_vAlignTable['u111'] = 'center';gv_vAlignTable['u129'] = 'center';gv_vAlignTable['u39'] = 'center';gv_vAlignTable['u171'] = 'top';gv_vAlignTable['u0'] = 'top';gv_vAlignTable['u63'] = 'center';gv_vAlignTable['u83'] = 'center';gv_vAlignTable['u8'] = 'top';gv_vAlignTable['u3'] = 'top';gv_vAlignTable['u146'] = 'top';gv_vAlignTable['u49'] = 'center';gv_vAlignTable['u148'] = 'top';gv_vAlignTable['u93'] = 'center';gv_vAlignTable['u167'] = 'top';gv_vAlignTable['u165'] = 'top';gv_vAlignTable['u117'] = 'center';gv_vAlignTable['u59'] = 'center';gv_vAlignTable['u137'] = 'center';gv_vAlignTable['u18'] = 'top';
u161.style.cursor = 'pointer';
$axure.eventManager.click('u161', function(e) {

if (true) {

	SetPanelVisibility('u30','','none',500);

}
});
gv_vAlignTable['u45'] = 'center';gv_vAlignTable['u22'] = 'top';gv_vAlignTable['u107'] = 'center';gv_vAlignTable['u35'] = 'center';gv_vAlignTable['u28'] = 'center';